# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: GalaxyBalaxyUpload

on:
  release:
    types: [published]

# .github/workflows/ci-cd.yml
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: Windows, macOS, Linux
    environment:
      name: pypi
      url: https://pypi.org/p/GalaxyBalaxyUpload
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    # retrieve your distributions here
              - name: pypi-publish
                uses: pypa/gh-action-pypi-publish@v1.8.11
            
